-- ============================================================
-- SEVELIN POS — Módulos de Compras, Órdenes de Trabajo y Ventas Pendientes
-- Archivo: sql/02-modulos-compras-ot-ventas.sql
-- Ejecutar en Supabase → SQL Editor. Es idempotente: puedes correrlo
-- varias veces sin romper nada de lo que ya existe.
-- ============================================================

-- ============================================================
-- 1. VENTAS: estado de pago
-- ============================================================
ALTER TABLE ventas
  ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'PAGADA',
  ADD COLUMN IF NOT EXISTS fecha_pago TIMESTAMP WITH TIME ZONE NULL,
  ADD COLUMN IF NOT EXISTS metodo_pago_final TEXT NULL;

-- Las ventas antiguas quedan coherentes: las "Por Pagar" pasan a PENDIENTE
UPDATE ventas
   SET estado = CASE WHEN metodo_pago = 'Por Pagar' THEN 'PENDIENTE' ELSE 'PAGADA' END
 WHERE estado IS NULL;

UPDATE ventas
   SET metodo_pago_final = metodo_pago
 WHERE metodo_pago_final IS NULL
   AND COALESCE(estado, 'PAGADA') = 'PAGADA'
   AND metodo_pago IS NOT NULL
   AND metodo_pago <> 'Por Pagar';

-- Restricción de valores permitidos (se crea solo si no existe)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ventas_estado_check'
  ) THEN
    ALTER TABLE ventas
      ADD CONSTRAINT ventas_estado_check CHECK (estado IN ('PAGADA', 'PENDIENTE'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_ventas_estado ON ventas (estado);

-- ============================================================
-- 2. COMPRAS Y GASTOS
-- ============================================================
CREATE TABLE IF NOT EXISTS compras (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha           TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  proveedor       TEXT,
  clasificacion   TEXT NOT NULL,
  costo_total     NUMERIC NOT NULL,
  descripcion     TEXT NULL,
  url_documento   TEXT NULL,   -- factura / boleta
  url_comprobante TEXT NULL,   -- comprobante de pago
  creado_en       TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Por si la tabla ya existía con menos columnas
ALTER TABLE compras
  ADD COLUMN IF NOT EXISTS descripcion TEXT NULL,
  ADD COLUMN IF NOT EXISTS url_documento TEXT NULL,
  ADD COLUMN IF NOT EXISTS url_comprobante TEXT NULL,
  ADD COLUMN IF NOT EXISTS creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compras_clasificacion_check'
  ) THEN
    ALTER TABLE compras ADD CONSTRAINT compras_clasificacion_check CHECK (
      clasificacion IN (
        'Mercadería / Productos para Reventa',
        'Activo Fijo (Maquinaria, Herramientas, Equipamiento)',
        'Insumos / Consumibles Taller',
        'Gastos Operativos (Servicios, Arriendo, etc.)'
      )
    );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_compras_fecha ON compras (fecha DESC);
CREATE INDEX IF NOT EXISTS idx_compras_clasificacion ON compras (clasificacion);

-- ============================================================
-- 3. ÓRDENES DE TRABAJO (Check-In / Check-Out de Servicio Técnico)
-- ============================================================
CREATE TABLE IF NOT EXISTS ordenes_trabajo (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_ot              TEXT UNIQUE NOT NULL,
  cliente_nombre         TEXT,
  cliente_rut            TEXT,
  cliente_telefono       TEXT,
  cliente_correo         TEXT,
  cliente_direccion      TEXT,
  dispositivo_categoria  TEXT,
  dispositivo_modelo     TEXT,
  dispositivo_sn         TEXT,
  dispositivo_enciende   TEXT,
  dispositivo_pin        TEXT,
  cargador_deja          BOOLEAN DEFAULT FALSE,
  cargador_tipo          TEXT,
  cargador_voltaje       NUMERIC,
  cargador_amperaje      NUMERIC,
  cargador_cable         BOOLEAN DEFAULT FALSE,
  accesorios             TEXT,
  falla_reportada        TEXT,
  obs_cliente            TEXT,
  obs_tecnico            TEXT,
  acepta_responsabilidad BOOLEAN DEFAULT TRUE,
  estado                 TEXT DEFAULT 'PENDIENTE',
  fecha_ingreso          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  fecha_entrega          TIMESTAMP WITH TIME ZONE NULL,
  retira_nombre          TEXT NULL,
  retira_rut             TEXT NULL,
  retira_firma_base64    TEXT NULL,
  creado_en              TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE ordenes_trabajo
  ADD COLUMN IF NOT EXISTS dispositivo_enciende TEXT NULL,
  ADD COLUMN IF NOT EXISTS creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ordenes_trabajo_estado_check'
  ) THEN
    ALTER TABLE ordenes_trabajo
      ADD CONSTRAINT ordenes_trabajo_estado_check CHECK (estado IN ('PENDIENTE', 'ENTREGADO'));
  END IF;
END $$;

-- Correlativo OT-000001: lo asigna la base de datos, así nunca se repite
-- aunque dos personas hagan check-in al mismo tiempo.
CREATE SEQUENCE IF NOT EXISTS ordenes_trabajo_numero_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE FUNCTION asignar_numero_ot()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.numero_ot IS NULL OR NEW.numero_ot = '' THEN
    NEW.numero_ot := 'OT-' || LPAD(nextval('ordenes_trabajo_numero_seq')::TEXT, 6, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_asignar_numero_ot ON ordenes_trabajo;
CREATE TRIGGER trg_asignar_numero_ot
  BEFORE INSERT ON ordenes_trabajo
  FOR EACH ROW EXECUTE FUNCTION asignar_numero_ot();

-- Si ya tenías OT cargadas, la secuencia parte después de la última
SELECT setval(
  'ordenes_trabajo_numero_seq',
  GREATEST(COALESCE((SELECT MAX(NULLIF(regexp_replace(numero_ot, '\D', '', 'g'), ''))::BIGINT FROM ordenes_trabajo), 0), 1)
);

CREATE INDEX IF NOT EXISTS idx_ot_estado ON ordenes_trabajo (estado);
CREATE INDEX IF NOT EXISTS idx_ot_fecha_ingreso ON ordenes_trabajo (fecha_ingreso DESC);

-- ============================================================
-- 4. STORAGE: bucket de documentos de compras
-- ============================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('compras-documentos', 'compras-documentos', TRUE)
ON CONFLICT (id) DO NOTHING;

-- Lectura pública de las URLs (los archivos se sirven al abrir el enlace).
-- La escritura queda solo para el backend, que usa service_role.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname = 'storage' AND tablename = 'objects'
       AND policyname = 'compras_documentos_lectura_publica'
  ) THEN
    CREATE POLICY compras_documentos_lectura_publica
      ON storage.objects FOR SELECT
      USING (bucket_id = 'compras-documentos');
  END IF;
END $$;

-- ============================================================
-- 5. RLS: nadie entra directo desde el navegador.
--    El backend usa service_role, que omite RLS.
-- ============================================================
ALTER TABLE compras         ENABLE ROW LEVEL SECURITY;
ALTER TABLE ordenes_trabajo ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 6. Comprobaciones rápidas (descomenta para revisar)
-- ============================================================
-- SELECT estado, COUNT(*), SUM(total) FROM ventas GROUP BY estado;
-- SELECT clasificacion, SUM(costo_total) FROM compras GROUP BY clasificacion;
-- SELECT numero_ot, estado, cliente_nombre FROM ordenes_trabajo ORDER BY id DESC LIMIT 5;
