-- ============================================================
-- SEVELIN POS — Módulo de Abonos y Encargos
-- Archivo: sql/04-abonos-encargos.sql
-- Ejecutar en Supabase → SQL Editor, después de los scripts 01, 02 y 03.
-- Es idempotente: puede correrse varias veces sin efectos secundarios.
-- ============================================================

-- 1. Encargos (pedidos, reservas y servicios con seña)
CREATE TABLE IF NOT EXISTS encargos (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ot_id            BIGINT NULL REFERENCES ordenes_trabajo(id) ON DELETE SET NULL,
  numero_ot        TEXT NULL,
  cliente_nombre   TEXT NOT NULL,
  cliente_rut      TEXT NULL,
  cliente_telefono TEXT NULL,
  descripcion      TEXT NOT NULL,
  monto_total      NUMERIC NOT NULL DEFAULT 0,
  monto_abonado    NUMERIC NOT NULL DEFAULT 0,
  saldo            NUMERIC NOT NULL DEFAULT 0,
  estado           TEXT NOT NULL DEFAULT 'PENDIENTE',
  observaciones    TEXT NULL,
  creado_en        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  actualizado_en   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Detalle de cada abono recibido
CREATE TABLE IF NOT EXISTS encargo_abonos (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  encargo_id  BIGINT NOT NULL REFERENCES encargos(id) ON DELETE CASCADE,
  monto       NUMERIC NOT NULL,
  metodo_pago TEXT NULL,
  nota        TEXT NULL,
  fecha       TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Estados permitidos
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'encargos_estado_check') THEN
    ALTER TABLE encargos
      ADD CONSTRAINT encargos_estado_check CHECK (estado IN ('PENDIENTE', 'PARCIAL', 'PAGADO'));
  END IF;
END $$;

-- 4. Mantener actualizado_en al modificar un encargo
CREATE OR REPLACE FUNCTION tocar_encargo()
RETURNS TRIGGER AS $$
BEGIN
  NEW.actualizado_en := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_tocar_encargo ON encargos;
CREATE TRIGGER trg_tocar_encargo
  BEFORE UPDATE ON encargos
  FOR EACH ROW EXECUTE FUNCTION tocar_encargo();

-- 5. Índices de consulta
CREATE INDEX IF NOT EXISTS idx_encargos_estado ON encargos (estado);
CREATE INDEX IF NOT EXISTS idx_encargos_ot ON encargos (ot_id);
CREATE INDEX IF NOT EXISTS idx_encargo_abonos_encargo ON encargo_abonos (encargo_id);

-- 6. RLS: solo el backend (service_role) entra a estas tablas
ALTER TABLE encargos       ENABLE ROW LEVEL SECURITY;
ALTER TABLE encargo_abonos ENABLE ROW LEVEL SECURITY;

-- 7. Comprobaciones rápidas (descomenta para revisar)
-- SELECT estado, COUNT(*), SUM(saldo) AS por_cobrar FROM encargos GROUP BY estado;
-- SELECT e.numero_ot, e.cliente_nombre, e.monto_total, e.monto_abonado, e.saldo, e.estado
--   FROM encargos e ORDER BY e.id DESC LIMIT 10;
