-- ============================================================
-- SEVELIN POS — Repuestos internos, cobro de OT en POS y notas privadas
-- Archivo: sql/05-repuestos-ot-pos.sql
-- Ejecutar en Supabase → SQL Editor, después de los scripts 01 a 04.
-- Es idempotente: puede correrse varias veces sin efectos secundarios.
-- ============================================================

-- 1. Catálogo comercial: marcar un producto como repuesto o insumo de taller
ALTER TABLE productos
  ADD COLUMN IF NOT EXISTS es_repuesto BOOLEAN DEFAULT FALSE;

-- 2. Notas privadas del técnico (nunca salen impresas al cliente)
ALTER TABLE ordenes_trabajo
  ADD COLUMN IF NOT EXISTS obs_internas TEXT NULL;

-- 3. Vínculo entre una venta y la orden de trabajo que se está cobrando
ALTER TABLE ventas
  ADD COLUMN IF NOT EXISTS ot_id BIGINT NULL REFERENCES ordenes_trabajo(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS numero_ot TEXT NULL;

CREATE INDEX IF NOT EXISTS idx_ventas_ot ON ventas (ot_id);

-- ============================================================
-- 4. REPUESTOS INTERNOS DE TALLER
--    Inventario propio del taller, no expuesto en el catálogo comercial.
--    Jerarquía: área/tipo → categoría base → modelo exacto.
-- ============================================================
CREATE TABLE IF NOT EXISTS repuestos (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area                 TEXT NOT NULL,          -- Teléfonos, Laptops, Consolas, Componentes SMD…
  categoria            TEXT NOT NULL,          -- Batería, Pantalla, FPC, Sub-Board, BIOS, Capacitores…
  modelo               TEXT NOT NULL,          -- 25Q128JVPQ, BN53, etc.
  descripcion          TEXT NULL,
  costo_unitario       NUMERIC NOT NULL DEFAULT 0,
  precio_venta         NUMERIC NOT NULL DEFAULT 0,   -- incluye mano de obra
  stock                NUMERIC NOT NULL DEFAULT 0,
  stock_minimo         NUMERIC DEFAULT 2,
  alerta_stock         BOOLEAN DEFAULT TRUE,
  ubicacion            TEXT NULL,
  stock_actualizado_en TIMESTAMP WITH TIME ZONE NULL,
  creado_en            TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_repuestos_area ON repuestos (area);
CREATE INDEX IF NOT EXISTS idx_repuestos_categoria ON repuestos (categoria);
CREATE INDEX IF NOT EXISTS idx_repuestos_modelo ON repuestos (modelo);

-- Evita duplicar exactamente el mismo repuesto
CREATE UNIQUE INDEX IF NOT EXISTS idx_repuestos_unico
  ON repuestos (lower(area), lower(categoria), lower(modelo));

-- 5. Repuestos y mano de obra asignados a una orden de trabajo
CREATE TABLE IF NOT EXISTS ot_repuestos (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ot_id          BIGINT NOT NULL REFERENCES ordenes_trabajo(id) ON DELETE CASCADE,
  repuesto_id    BIGINT NULL REFERENCES repuestos(id) ON DELETE SET NULL,
  producto_id    BIGINT NULL REFERENCES productos(id) ON DELETE SET NULL,
  nombre         TEXT NOT NULL,
  cantidad       NUMERIC NOT NULL DEFAULT 1,
  costo_unitario NUMERIC NOT NULL DEFAULT 0,
  precio_unitario NUMERIC NOT NULL DEFAULT 0,
  cobrado        BOOLEAN DEFAULT FALSE,
  creado_en      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ot_repuestos_ot ON ot_repuestos (ot_id);

-- 6. El detalle de venta puede apuntar a un repuesto interno
ALTER TABLE venta_items
  ADD COLUMN IF NOT EXISTS repuesto_id BIGINT NULL REFERENCES repuestos(id) ON DELETE SET NULL;

-- 7. RLS: solo el backend (service_role) entra a estas tablas
ALTER TABLE repuestos    ENABLE ROW LEVEL SECURITY;
ALTER TABLE ot_repuestos ENABLE ROW LEVEL SECURITY;

-- 8. Comprobaciones rápidas (descomenta para revisar)
-- SELECT area, categoria, COUNT(*), SUM(stock) FROM repuestos GROUP BY area, categoria;
-- SELECT o.numero_ot, r.nombre, r.cantidad, r.precio_unitario, r.cobrado
--   FROM ot_repuestos r JOIN ordenes_trabajo o ON o.id = r.ot_id ORDER BY r.id DESC LIMIT 20;
